spring.application.name=hogotaro

#jspの置き場所
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#DB関連
spring.datasource.url=jdbc:mysql://localhost:3306/hogotaro?serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.web.error.whitelabel.enabled=false